### ISSUE TITLE
Scrollbar flickering when scrolling

### ISSUE THREAD

**Issue by BZembrodt-BP** [Sergio70/AceEditorV14#58]
See attached Screen recording. When I try to scroll in the editor using the mouse wheel, the vertical scrollbar flickers in and out. Scrolling by dragging the bar is completely impossible.

The Issue seems to be that the default value for the maxLines is set to an Object containing Infinity https://github.com/Sergio70/AceEditorV14/blob/5a661290de0f4a7935086f1aa226a6af7c694c66/src/main/resources/META-INF/resources/frontend/%40f0rce/ace-widget/ace-widget.js#L126 instead of a number. This does not work correctly with the underlying ace editor, since a Number or Falsy value is expected, not an Object.

As a workaround I set the maxLines to 0 manually in our Java-Code (`aceEditor.setMaxlines(0);`), but I think this should be fixed in general. Im not sure though what the best default value would be here. 0 works for our usecase, but maybe Infinity (without being packed in an object) would also work.

![Scrolling](https://user-images.githubusercontent.com/81411601/112605740-ea3a1880-8e17-11eb-8639-c4d3c45fdf40.gif)

**Comment by F0rce** [comment]
Hello @BZembrodt-BP;

I was aware of this issue and worked the last few weeks, to get around it pretty neat.

I have released a completely new version of the ace editor, where Lit-Element is used in the frontend instead of Polymer 3. It fixed the flickering for me and the performance also improved. 

https://vaadin.com/directory/component/ace/1.0.1
https://docs.f0rce.de/ace

Could you give it a try and tell me afterwards, if it solved your Problem?

Sorry for the late reply,
David

**Comment by BZembrodt-BP** [comment]
Hi @F0rce,
I tried out the new version and as far as I can tell it works without issue (the scrollbar flickering is gone too). I will test it a bit more thoroughly but will probably stick with this solution.
Thank you very much for your help.

Have a nice day
Benjamin
